version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
    ports:
      - "3307:3306"

    volumes:
      - db_data:/var/lib/mysql

  server:
    build: ./server
    container_name: todo-server
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo_app
    command: sh -c "npm install -g wait-port && wait-port mysql:3306 && node index.js"

  client:
    build: ./client
    container_name: todo-client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db_data:
